name: Build BitcoinPoW Core Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang ccache build-essential cmake pkg-config python3-zmq libevent-dev libboost-dev libsqlite3-dev libdb++-dev systemtap-sdt-dev libzmq3-dev qtbase5-dev qttools5-dev qttools5-dev-tools qtwayland5 libqrencode-dev -y

      - name: Build BitcoinPoW Core
        run: |
          ./autogen.sh
          ./configure --with-gui=qt5
          make -j$(nproc)

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bitcoin-pow-core-linux
          path: |
            src/bitcoin-powd
            src/bitcoin-pow-qt
            src/bitcoin-pow-cli
            src/bitcoin-pow-tx
            src/bitcoin-pow-util
